### PR TITLE
Add detection for Kobo directory location on Linux

### PR DESCRIPTION
**Pull request by lkcv**
Adds detection for the Kobo directory on Linux and stores the location in a file for quicker subsequent access (in ~/.config/calibre). This is done because there's no assumed default location for Kobo on Linux since it runs under Wine and can be in any prefix.

Sorry for creating two PR's back-to-back for this. I was having some trouble squashing commits after trying to fix a typo and ended up removing all commits in the last PR, causing it to be automatically closed.

### CODE REVIEW

**Comment by apprenticeharper** [comment]
I'm going to accept this without checking it. Thanks for the contribution.

**Comment by Artoria2e5** [comment]
I am honestly a bit against this approach since it's so expensive (it looks under EVERYWHERE, including outside of the user's home directory). It might be best to just allow a setting to specify the WINEPREFIX like what's been done for the main DeDRM plugin's ADE and Kindle wine extraction. The environmental expansion can be done through commands like `wine cmd /nologo /c echo %LOCALAPPDATA%`.

Even if a wine-independent search is to be done, the current implementation is... IDK. Some recommendations include:
* Starting with `~` instead of `/`.
* Using `f.write()` instead of the stdout-print magic.

**Comment by lkcv** [comment]
Thank you for the recommendations. I agree that it's probably better to not have the script look everywhere for a directory that probably exists somewhere under ~/.wine for most users and that using f.write makes a lot more sense than whatever I was doing with stdout.

I've already tested these two changes and of course it's much faster since the script is looking only under ~/ so I'm planning on implementing the WINEPREFIX changes as well if the user would just prefer to supply a value to that and skip the directory search altogether.

Do you have a better idea for storing the directory location so that subsequent directory searches aren't needed (like I'm currently doing with the file in ~/.config/calibre)?

**Comment by Artoria2e5** [comment]
The cache location is fine to me.

**Pull request merged**
