### PR TITLE
Initial Appveyor+PyInstaller Build (standalone Windows exe/folder)

### PR DESCRIPTION
**Pull request by nelsonjchen**
I wanted a version that could run in a VM but I found the instructions would be a bit hard and scary for those who aren't familiar with Python. And for those who are a lot more familiar with Python, it was a bit of a downer to follow the instructions to the letter and have to install stuff globally without virtual environments, or stray off the path and go about it without installing globally. 

So I made this branch. It's a slight addition of a few batch scripts and some configuration for Appveyor to produce a PyInstaller build of DeDRM. The PyInstaller build does not require Python 2.7 or PyCrypto to be installed globally on the system. All you need to run this script is the generated folder with these EXEs and some DLLs in it. It's self-contained, like other popular Python applications such as Dropbox, [Anki](https://github.com/dae/anki), and especially [McEdit2](https://github.com/mcedit/mcedit2/blob/master/appveyor.yml) of which I heavily used as reference. 

I did make one modification to the underlying scripts. I called [`freeze_support()`](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.freeze_support) in the `.pyw` file. This is required for the `multiprocessing` package to work in this environment. There did not appear to be a regression for a non-frozen "build".

**The results of which, are located [here in Appveyor](https://ci.appveyor.com/project/nelsonjchen/dedrm-tools/build/artifacts)**. You can download the zip, unzip it onto a virgin Windows 8.1+ system, and run the tools. Drag and drop works, as does the GUI. I do not know if this works on Windows 7 as it's very YMMV. I also should note that I've only tested this with ADE 2.0.1. I'm not sure if the DRM that uses ALF works and I'm not sure if the Kindle one works. Reports would be appreciated.

I haven't updated the READMEs or documentations yet as I simply wanted to get this out for some comments/guidance. May I suggest adding a "Binaries" section to the `README.md` like in [dnspy](https://github.com/0xd4d/dnSpy#binaries)? I'm not sure what the desired release process should be so I'll leave that up to the owners of this repo. From @wzyboy 's work, it definitely seems to be in a state of flux.

I also want to note that it might be possible to get rid of the Mac build and build a Windows+Mac+Linux UI/target from one codebase if PyInstaller is used to package this as a Mac App. I haven't tried that yet though.

### CODE REVIEW

**Comment by apprenticeharper** [comment]
I am unfamiliar with Appveyor. It seems to me that this might be a useful addition, but I don't have the expertise to really evaluate it. So long as it's scripts that generate any binary executables on the user's machine and not in the repository, I'm happy.

The Mac and Windows (actually generic python) applications have been rather neglected compared to the calibre plugin. Mainly because the calibre plugin is a lot easier to install and use.

If you can fix this pull request to have no conflicts with the repository now that I've merged the changes to the code organisation, I'd be happy to include it fr those who prefer the application to the plugin.

Harper.

**Comment by nelsonjchen** [comment]
Appveyor is a public continuous integration system that many projects on GitHub use for continually building software from their source repositories. Appveyor is commonly used for Windows software as they provide access to Windows build slaves for free to open source projects. Many OSS projects targeting Windows, not just Python projects, use Appveyor to automatically provide source-to-binary builds and to also deploy and release the builds. 

Using a CI system to handle that is the answer to "I just want only source code in my repo, but how do I put out releases and keep them and the process versioned without committing generated or binary artifacts into the repo? 🤔". Much like @wzyboy's refactoring where common source code is refactored so that manual copying of modules between versions is reduced, it's a similar "Don't Repeat Yourself" thing. 

What Appveyor does is get notifications from GitHub about updates to the source code in the repository, start a generously developer tooling equipped Windows VM, downloads the source code in said VM, and runs commands in said VM specified by the developer to build, test, and release the software. There are currently no automated tests so we can only use the build and release portion but that's still very good. Per your concern, these standalone and binary build artifacts/executables are not recommitted back into the repository nor are they generated on the user's machine as they are generated on Appveyor's machine. Users are to download and use these artifacts/executables from wherever we configure the build system to deposit them.

I would suggest getting Appveyor setup on this repository and initially just building the binary releases of commits and just storing them there for now. This is something I cannot do in this pull request nor as a non-owner as it requires some level of Admin access on the repository which I don't have. You'll have to go to appveyor.com and login with the "apprenticeharper" GitHub account and add this repository. 

screen shot 2018-06-02 at 9 19 11 am

After that, I would suggest checking these two boxes and saving the settings at this URL: https://ci.appveyor.com/project/apprenticeharper/dedrm-tools/settings

screen shot 2018-06-02 at 9 24 48 am

In the future, Appveyor can even be configured to deploy and attach these additional self-contained Windows builds to the GitHub releases you are already tagging, pushing, and manually building. That probably should be a another pull request or issue as this Appveyor system is tested out.

As for the calibre plugin popularity, personally, I think of Calibre as the iTunes of ebook management. It's a bit big, can screw around with the system a tad bit too much (sometimes to the point of a security concern as Calibre's fights with OS vendors have shown), and kinda resource intensive. The standalone apps are more popular for the people who are fans of file system folders, WinAmp, and foobar2000 and so on. 

All said, here's what I'll be doing for this PR.

* Evaluate and fix the merge conflicts/new incompatibilities with @wzyboy's changes.
* Update the main README.md to have a build badge to where the Appveyor page for the project would be if it was enabled for the apprenticeharper/DeDRM_tools repository.
* Update the sub README.md files for the Windows folder to describe and link to the Appveyor page.

**Comment by nelsonjchen** [comment]
Wow, @wzyboy 's changes changed the structure quite a lot. I'll see if I can get his script automatically running and building the zip w/EXE folders on Appveyor/Windows.

**Comment by nelsonjchen** [comment]
Unlike other CI systems on GitHub, I am not able to pre-add a badge. I think we'll have to wait for someone with Admin on this repo to do that. 

Besides that, I've now rebased all my changes on @wzyboy 's changes. I took the opportunity to integrate this work with @wzyboy 's  new `make_release.py` script as well. There is now a "windows_standalone" `contrib` build that takes the script version and builds an app out of it and includes it as an option in the distributed ZIP. This build will not be built on non-Win32 platforms and introduces a dependency on Pyinstaller for users of the `make_release.py` script . I also wrote a small readme that just points users to the non-bundled Python script version's readme which is copied to the destination.

https://ci.appveyor.com/project/nelsonjchen/dedrm-tools/build/1.0.21

Please take a look.

**Comment by wzyboy** [comment]
@nelsonjchen Wow! Great work! Automatic builds on Windows hosts looks so promising.

AFAIK, the `make_release.py` script now outputs different files when running on Windows / non-Windows platforms, right? Since Windows standalone exe could only be generated on a Windows host, does this mean Harper needs to use artifacts built by AppVeyor now?

**Comment by nelsonjchen** [comment]
An alternative release approach would be to modify `make_release.py` to generate an additional zip with only the standalone EXE folder on Windows. I integrated the current generation script into `make_release.py`'s preexisting ZIP simply because it was already there. This may not be the wisest choice though.

Yeah, if he or she wants the most featured ZIP and one that is probably most useful, it should be built on a Windows platform. Not necessarily automatically by Appveyor, but definitely Windows.

**Comment by nelsonjchen** [comment]
It is a bit weird to include *all* the builds in one zip though. That probably comes more from a time when the stuff here was more directly executable straight from checkout.

**Comment by nelsonjchen** [comment]
I've rebased my changes on the latest master. 

Please let me know how we can work to get this in. A standalone Windows App would be great as is the possibility of reducing a SKU in the future by eliminating the Mac app in favor of just a PyInstaller Mac GUI.

**Comment by nelsonjchen** [comment]
Also, in the time since I've made this PR, GitHub released their Checks API and also announced a GitHub marketplace partnership with Appveyor and a few other CI systems. I would recommend installing Appveyor on this repository by [going through that mechanism](https://github.com/marketplace/appveyor) instead.

**Comment by apprenticeharper** [comment]
I have limited time for this project. But you seem very keen and capable, so I've sent a contributor invite to you.

There is a problem with wzyboy's refactoring - copying the Mac droplet file on WIndows causes it to lose its executable bit. I'm not sure how best to fix this. But I suppose I should comment on that issue about it.

**Comment by nelsonjchen** [comment]
@apprenticeharper Thanks, I've accepted it. However, to setup Appveyor, I'll probably need Admin. All I have is Write though. But my thoughts are that maybe Appveyor isn't the way to go. I think it might be preferable to use Travis CI though here:

https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup

Could you install the "Open Source" plan into this repository? 

The reason is that there have been some really serious developments since my the last comment about the CI world as well:

* Microsoft Azure Pipelines has opened shop with unlimited minutes for builds for OSS projects. They support Linux, Windows, and Mac under one roof. They're not as popular though. Visual Studio Code was using a combination of Travis and Appveyor and has since migrated to this so they can have all their builds under one roof.
* Travis CI has introduced support for Windows in addition to their existing Linux and Mac support. Travis CI is a lot more popular amongst the existing OSS community. While their Linux and Mac support is more mature than Windows, I feel that they are much more familiar to GitHub users and I would like to go with them.

**Comment by wzyboy** [comment]
> There is a problem with wzyboy's refactoring - copying the Mac droplet file on WIndows causes it to lose its executable bit.

Hmm. I checked `shutil.copytree()` function, it *does* using `shutil.copy2()` as the default copy function, which means all file stats are preserved as much as possible (like `cp -p`). So it turns out that Windows Python could not preseve the exectuable bit on copying files.

**Comment by nelsonjchen** [comment]
My vision for this is that the Mac builds for the future aren't built on Windows. They are built on macOS, where tooling honors and supports macOS filesystem attributes, and produce a ZIP with only Mac builds that don't have that problem.

**Comment by sidick** [comment]
As a UNIX admin, building on Linux for Mac makes far more sense and reduces the chances of file permission issues

**Comment by nelsonjchen** [comment]
If a Linux job on Travis CI works well enough to "build" that, sure. The faster "build" speeds would be nice. It's just file copying. If some bits still fall off for some reason, like with [macOS's MIME-like UTI file type system](https://en.wikipedia.org/wiki/Uniform_Type_Identifier), we'll need to reconsider that.

**Comment by nelsonjchen** [comment]
There have been even more developments: GitHub will now be offering a CI of some sort. No Windows though. Also, limited access.

**Comment by nelsonjchen** [comment]
I'm much more in favor of an Azure Pipelines-based build nowadays. That said, the PyInstaller stuff should be ported over to it.

**Comment by nelsonjchen** [comment]
Oh, and Azure Pipelines can do that generate a single ZIP thing too which was impossible on any other CI platform.

**Pull request closed without merging**
