### PR TITLE
Finish .kinf2018 support and add KFX v2/v3 support

### PR DESCRIPTION
**Pull request by apprenticesakuya**

### CODE REVIEW

**Comment by ZolaLa9** [comment]
Thank you so much!!!!!!!!!!!!

**Comment by juandpinto** [comment]
You, my friend, are a godsend 🙏

**Comment by DB99** [comment]
Fantastic work!  Thank you.

**Comment by apprenticeharper** [comment]
Astonishing. Very many thanks for all your hard work on this, Apprentice Sakuya

**Pull request merged**
