### PR TITLE
Add missing imports flagged in GitHub Actions

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/apprenticeharper/DeDRM_tools/actions

### CODE REVIEW

**Comment by apprenticeharper** [comment]
I don't think these are really missing. That is, the code runs without them. I'm unwilling to change working code because a style checker says to do it.

**Comment by cclauss** [comment]
```
./make_release.py:24:25: F821 undefined name 'core_dir'
    shutil.make_archive(core_dir, 'zip', core_dir)
                        ^
```
Where is `core_dir` defined or imported on lines 1 through 23 of ./make_release.py ?

**Comment by cclauss** [comment]
Given that `make_calibre_plugin()` is _never_ called, this function is probably dead code.

**Comment by apprenticeharper** [comment]
Let's fix this by removing dead code, eventually.

**Pull request closed without merging**
