### PR TITLE
"promt" doesn't make any sense

### PR DESCRIPTION
**Pull request by keshavgbpecdelhi**
I think it may be a silly mistake or something because the other prompts are written well except this. Just to webpage will not look authentic by using a wrong spelling so writing the sentence like as follows :
Clicking this button will prompt you to enter a new name for the highlighted key in the list.

### CODE REVIEW

**Comment by SamMorrowDrums** [comment]
Not against improvements in language, but these are blatantly attempts to get a free t-shirt for Hacktoberfest...

https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama

**Comment by keshavgbpecdelhi** [comment]
> Not against improvements in language, but these are blatantly attempts to get a free t-shirt for Hacktoberfest...
> 
> https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama

After judging things in your code I come to the attempt for this pull request of typo correction. I know it's not that good, but it is important. Also I read that article of spamming in name of hacktober fest so I know they are spamming with shits in the name of pull request, and if you think this pull request is not genuine, then it's ok. Don't accept it no issue at all. Just don't neglect it. Every single typo is a bad impression for clients and users and sorry if I wasted your time by sending this genuine request (for me) or might be a bad PR for you 🙏

**Comment by SamMorrowDrums** [comment]
Don't worry @keshavgbpecdelhi it's not up to me anyway just there's a lot of "low quality" PRs floating around at the moment. And submitting so many individual PRs for typo fixes is rare. Usually I see single PRs with a batch of related changes.

I don't really mind whether this is about a t-shirt or not, but I don't want to encourage too much overhead for maintainers with large numbers of PRs where one would suffice.

Anyway, as I say - it's not up to me, and if you do just want to help the tool, then great!

**Comment by keshavgbpecdelhi** [comment]
> Don't worry @keshavgbpecdelhi it's not up to me anyway just there's a lot of "low quality" PRs floating around at the moment. And submitting so many individual PRs for typo fixes is rare. Usually I see single PRs with a batch of related changes.

Agreed! The reason for sending different PRs for typo purpose is - the code is arranged in different html  files and you know I checked around all html flies so how can a single PR will do the typo correction work in other file for instance, [pull request 1270](https://github.com/apprenticeharper/DeDRM_tools/pull/1270) is for [README.md](https://github.com/apprenticeharper/DeDRM_tools/pull/1270/commits/e6f51c8db2d5c8ae8c6f396d66763f21832f7ea9#diff-04c6e90faac2675aa89e2176d2eec7d8) while [PR 1269](https://github.com/apprenticeharper/DeDRM_tools/pull/1269/commits/971db9ae71b714613ff2eada5a0c35f755cc9007) is for [DeDRM_plugin >DeDRM_Kindle for Mac and PC Key_Help.html file](https://github.com/apprenticeharper/DeDRM_tools/pull/1269/commits/971db9ae71b714613ff2eada5a0c35f755cc9007#diff-cefc2c98cbdc3a1821d306aa5197bd1e) 

So how can we write a single PR for different folders or even different files of the same folder, there is no such option.. if you have any idea about this it would be glad to know from you.

> I don't really mind whether this is about a t-shirt or not, but I don't want to encourage too much overhead for maintainers with large numbers of PRs where one would suffice.

Agreed! but still I would say the same those typos needed to be corrected. Idc whether they merge mine or do by themselves. And I am working on another project rn..last year also I didn't get any shirt even after 5 PRs so I also lost hope of getting it this time also and you know only those t-shirts which are rare to get are my choice, as spammers are getting these t-shirts so it's value is decreasing in my eyes, and yes I keep my words.

> Anyway, as I say - it's not up to me, and if you do just want to help the tool, then great!

Thanks @SamMorrowDrums dear. Hope you are contributing genuine PRs unlike me ( the noob :c ).

**Comment by SamMorrowDrums** [comment]
> So how can we write a single PR for different folders or even different files of the same folder, there is no such option.. if you have any idea about this it would be glad to know from you.

You create a branch, make all the changes and commit them, then make a pull request to merge your branch into master.

Maybe you're using the GitHub interface directly? PRs can change any number of files. There's no restriction. That's why pull requests are not part of git (but are added to things like GitHub). They are just a way to move code between branches with an interface to make comments, review code and approvals, which also allow people without privileges to suggest changes to other people's code.

But you can ask to pull any branch from your version of the code into this one, and you can create as many changes as you like within a branch first.

**Comment by keshavgbpecdelhi** [comment]
> Maybe you're using the GitHub interface directly?

Yes right! Idk how to interact with github using git. Not much idea of branches, master and all. And often get confused what to do after git clone command, obviously because lack of knowledge..that's why I use only github for PRs. And I m still learning how to interact using git. 

> But you can ask to pull any branch from your version of the code into this one, and you can create as many changes as you like within a branch first.

Thanks for telling this. Now I think after understanding git I would be able to send a single PR for typos.

**Pull request merged**
