### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by ableeker**
Python 3 fixes for Customize dialog.

### CODE REVIEW

**Comment by ableeker** [comment]
This should fix the imports/exports for all key files (except possibly B&N, as I don't have any of these files).
Decryption of epubs should work as well.

**Comment by ableeker** [comment]
More Python 3 fixes.

**Comment by macmiranda** [comment]
works for me on Windows for EPUB files

**Comment by apprenticeharper** [comment]
Thanks. I've merged and will check once other pull requests have merged.

**Pull request merged**
