### PR TITLE
Fixed syntax, removed unnecessary whitespace

### PR DESCRIPTION
**Pull request by spaz926**
Not sure if this script still works, but I fixed the syntax.

### CODE REVIEW

**Comment by apprenticeharper** [comment]
If someone can verify that the script still works, I'll be happy to include this update.

**Comment by ElleKayEm** [comment]
This script broke a little over a year ago when B&N completely changed the Nook Library page.  I haven't heard of anyone updating it to work with the new page layout.

**Comment by apprenticeharper** [comment]
Thanks. Perhaps I should remove it from the archive?

**Comment by ElleKayEm** [comment]
A note in the readme would be good.  Be nice to see it updated, but I suppose no one is motivated enough to look into it.

**Comment by spaz926** [comment]
Unfortunately I don't own any B&N ebooks to test the script. Just ran across it and noticed the incorrect syntax.

**Comment by ElleKayEm** [comment]
If anyone wants to look at it, there are free B&N books here:
http://www.barnesandnoble.com/b/nook-books/free-ebooks/_/N-8qaZry0

(Always double check that it says free before clicking.)

**Comment by apprenticeharper** [comment]
I think this is now outdated.

**Pull request closed without merging**
