### PR TITLE
removed Requiem website

### PR DESCRIPTION
**Pull request by wxl**
The hidden service serving the Requiem website is down and has probably [been down][1] for quite a while. 

[1]: http://forums.peerblock.com/read.php?13,13983,13983

### CODE REVIEW

**Comment by Alphasee** [comment]
I know this might be a dated conversation, but on a relevant note, DRmare seems to resolve what you guys are talking about, unless I'm mistaken.

**Comment by wxl** [comment]
@Alphasee it does seem like DRmare is a direct replacement for Requiem, in that it appears to remove FairPlay, and so works over a wide variety of Apple media (including iBooks). Ironically, I don't even have an Apple-thing, so I can't really comment more on that, but you might want to add a pull request if you can confirm it's the real deal.

@apprenticeharper I don't know how I missed your note about the spelling mistake. Probably too late, but fixed regardless.

**Comment by Alphasee** [comment]
I don't either, I just uncovered it (and good non-spammed reviews). Thanks
guys for helping with an awesome project!

**Comment by ElleKayEm** [comment]
I don't have an iThing either, but after a quick look, it doesn't seem like DRmare would be a replacement for Requiem here -- commercial product, doesn't work on iBooks (only iTunes audio & video).

**Comment by wxl** [comment]
Yeah if you dig a bit deeper there's instructions on at least
[converting audiobooks][1] and on a [general Fairplay removal page][2]
sort of implies that there may be support for iBooks. Everywhere else
it's more or less "music, movies, etc." so what "et cetera" here means
is an exercise I leave for the iReader.

[1]: https://www.drmare.com/drm-audiobooks/
[2]:
https://www.drmare.com/drm-knowledge/remove-fairplay-drm-from-itunes-digital-media.html

**Comment by apprenticeharper** [comment]
Merged. Thanks.

**Pull request merged**
