### PR TITLE
update obok.py with new hashes - support obok cmd line usage

### PR DESCRIPTION
**Pull request by norbusan**
HI apprenticeharper

here is a pull request for the changes implemented by minxmanx in the comment section. He added the hash for the new desktop key, and changed the code that it is easier to add new hashes.

Hope that helps

Norbert

### CODE REVIEW

**Comment by fuffolo** [comment]
Goon morning.
I have connected my Kobo (3.19.xxx) to my PC linux mint equipped.
I am not able to decrypt ebook using macaddress of ebook (seen in 'impostazioni') and your ultimate
key.
Can you suggest where i am wrong? Do you need more info?
Thanks

**Comment by fuffolo** [comment]
I forgot.
Need to add sys.platform.startswith('linux') in __getmacaddrs (self)

**Comment by norbusan** [comment]
@fuffolo could you ever decrypt books using obok? Do you use the latest obok plugin? Did you run calibre in debug mode?

**Comment by fuffolo** [comment]
Hello Norbert.
I thank you for replay.
I use obok.py Version 3.1.6 September 2015 with hash-key '88b3a2e13'. My
kobo ereader is updated to software release 3.19.5613
(4b76aa47bd, 04/12/15) as kobo options said.
I know quite well python and linux and I use obok.py directly with tkinter
interface
I connect Kobo device by usb to my linux pc that mounts kobo filesystem. So
obok.py read /media/.../KOBOeReader/.kobo/KoboReader.sqlite
Ebook titles are listed and free-drm downloaded by obok.
Obviously as mac address I add the address reported in Kobo device in
hardware details:
Indirizzo MAC: 78:45:61:::: ecc
I think that ifconfig read the mac address of PC and is not useful to
decrypt work (I have not installed kobo-desktop!)
But Drm-ed kepub are not decrypted and error
   -Could not decrypt book with any of the keys found
appear.
I have not modified obok core code, only interface.
Any suggestion???



2015-12-26 15:56 GMT+01:00 Norbert Preining <notifications@github.com>:

**Comment by norbusan** [comment]
Ok, checking the code I see that using the cmd-line version might not work out. I will try myself and see whether it works here or not.

Thanks

**Comment by norbusan** [comment]
One more comment - the command line version does not support for now the out-finding of serials. What changes did you do to the source code? Can you send me a link to your version?

**Comment by fuffolo** [comment]
Sure!

I attach my cli version using argparse. I am coding a bit tkinter check
list to view ereader library and extract epub, but it is not ready yet.
As you know kobo is linux device, so when you connect to linux pc all kobo
filsystem is mounted an you can navigate it as local.
No need serials. You can check usb device only to assert the connection
(yes, sometime  I try to use kobo without connect it!!)
But I seen that serials items are attached to macaddress, so i add to
serials list the kobo ereader macaddress.
All very simple...but doesn't run! Damned!
Thanks for you time


2015-12-27 2:00 GMT+01:00 Norbert Preining <notifications@github.com>:

**Comment by norbusan** [comment]
Hi, it seems the attachment didn't go through. Can you please send it to me at norbert@preining.info thanks

**Comment by norbusan** [comment]
Hi Apprentice Harper

I have updated the  pull request, it contains now two changes:
- fixes from the comment section about new hashes (by minxmanx)
- adaptions by me to make the obok.py script usable on the command line in Linux:
  - move the serial detection code into the obok.py script
  - add a command line argument to pass in the device directory

I hope you consider these improvements.

Thanks

Norbert

**Comment by timofonic** [comment]
@apprenticeharper

Are you there? :)

**Comment by fuffolo** [comment]
Yes. I have changed code as you say and all is ok.
Thanks very much!
Now I am thinking how discard and decrypt my google ebooks!!!!
I want all my ebooks to read everywhere and with all my devices!

**Comment by apprenticeharper** [comment]
Thanks for your work on this. I've merged this pull request, although I may well make more changes before uploading a new release.

**Comment by norbusan** [comment]
Thanks a lot! Thanks for your work on all that!

**Pull request merged**
