### PR TITLE
Support multiple input Kindle files

### PR DESCRIPTION
**Pull request by dunesmopy**
Sample bulk/batch usage:

    @echo off
    setlocal

    SET IN_DIR=%USERPROFILE%\My Documents\My Kindle Content
    SET DEST_DIR=%IN_DIR%_drmfree
    SET KEY_FILE=mykeyfile.k4i

    mkdir "%DEST_DIR%
    k4mobidedrm.py -k %KEY_FILE% "%IN_DIR%" "%DEST_DIR%

    echo done, see %DEST_DIR%
    cd /d "%DEST_DIR%"
    start .

    endlocal

### CODE REVIEW

**Comment by apprenticeharper** [comment]
I don't have any great objection to this change. It doesn't impact the plugin or the applications, only stand-alone use.

But I'd like to see the following changes before I merge it in:

1) Version number updated to 5.5 in the version variable.
2) If we're going to allow a variable number of input parameters, we ought to allow them all to be either files or directories of files.
3) It must also look for .azw1, .azw3, .azw4, .prc, .mobi, and .pobi files in any specified directories.

**Comment by dunesmopy** [comment]
@apprenticeharper good feedback :+1:. PR updated with new diffs. :crossed_fingers:

**Comment by apprenticeharper** [comment]
One last question before I merge. When did the glob library get added? I'd hate to make the script require a late version of python 2.x if we don't need to.

**Comment by dunesmopy** [comment]
@apprenticeharper sorry, only just saw this. `glob` is very old, introduced in Python 1.4 and all 2.x versions  support it. For reference see https://pymotw.com/2/glob/

**Comment by apprenticeharper** [comment]
Thanks for indulging my laziness in not googling it myself. Merging.

**Pull request merged**
