### PR TITLE
WIP: Make DeDRM kindlekey.py work on Python3.8

### PR DESCRIPTION
**Pull request by tartley**
This addresses https://github.com/apprenticeharper/DeDRM_tools/issues/1299

But is still WIP: Many non-trivial fatal errors are still not fixed.

Fix the code to run on Python3.8, including:
* Run 2to3 on kindlekey.py
* Fix the error dialog to display _"This script only runs 
  on Windows or OS X"_, instead of producing a traceback.
  (This was not a Python2/3 thing, it was just broken.)
* Convert some string literals (eg "hello")
  to byte string literals (eg b"hello").
* Convert some unicode literals (eg u"hello")
   to regular string literals (eg "hello").
* All instances of unicode type replaced by str.
* Uses of 'ord' on characters from a bytestring are redundant.
  Individual bytes from a bytes object are already integers.
* Uses of 'chr' to convert characters back to a 1 character string
   to something like bytes([integer, ...]) instead.

### CODE REVIEW

**Comment by tartley** [comment]
Current status: A tk window launches, but contains a traceback:
```
Traceback (most recent call last):
  File "DeDRM_plugin/kindlekey.py", line 1799, in gui_main
    keys = kindlekeys()
  File "DeDRM_plugin/kindlekey.py", line 1687, in kindlekeys
    files = getKindleInfoFiles()
NameError: name 'getKindleInfoFiles' is not defined
```
I'm currently trying to figure out why there are two functions with that name, why neither of them are defined, which one should be defined at this point, and how to make it so...

**Comment by tartley** [comment]
Fixed the above, by fixing the call to the error dialog which produces the error "This script only runs on Windows or OS X".

So now I might have to remember out how to do Python development on Windows. It's been more than ten years, let's go fire up the gaming computer...

**Comment by tartley** [comment]
I've been fixing each problem as it occurs during script startup. Based on the fixes so far, I've accumulated some rules of thumb that the whole source should probably be audited for:

1. Many string literals (eg "hello") should probably be converted to byte string literals (eg b"hello").
2. All unicode literals (eg u"hello") should be converted to regular string literals (eg "hello").
3. All instances of unicode type should be replaced by str.
4. Uses of 'ord' on characters from a bytestring are probably redundant. Individual bytes from a bytes object are already integers.
5. Uses of 'chr' to convert characters back to a 1 character string should probably be `bytes([integer])` instead.

**Comment by apprenticeharper** [comment]
I'm sorry to have duplicated your effort, but I'm not going to merge this, as it almost certainly conflicts with my fixes for kindlekey (Mac - still to do PC compatibility)

**Comment by tartley** [comment]
@apprenticeharper  Understood, and that's fair enough. Thanks for the info. For what it's worth though, my fixes focus on the Windows path, so there might be some diffs in here that are useful and not covered by your branch. Let me know whether you'd like me to pick this task up again at some point, and I'll be happy to try and help. I understand if it's easier to just do it yourself. All good.

**Comment by tartley** [comment]
Also! You'll probably want the fix I made to fix the error dialog when running on an unknown OS. If you like I can split this into a tiny PR of its own.

**Comment by apprenticeharper** [comment]
Yes please to the error dialog. I'll try to merge in it quickly.

I would be delighted to have the code refactored to make testing and maintenance easier. But perhaps after we've got a working calibre 5 plugin.

**Comment by apprenticeharper** [comment]
I think you now have full access to this repository, so feel free to merge in changes yourself.

**Pull request closed without merging**
