### PR TITLE
[WIP] Py3 conversion

### PR DESCRIPTION
**Pull request by norbusan**
I have taken the changes from PR https://github.com/apprenticeharper/DeDRM_tools/pull/850 and tried to convert the code base to Python3. The current status is that Calibre can load the plugin, configuration works.

I got stuck in wine errors when trying to import a azw3, but that might be a local configuration error in wine.

I would appreciate if others give it a try and help improve. We need to look forward to 2020 when Python2 is deprecated.

### CODE REVIEW

**Comment by 2743d2** [comment]
I cloned your commit ee9ef17. Got a fresh install on Calibre v 4.5 sucessfully.
But got problem when DeDRM try to search for Kindle for PC encryption key.
image
On Win10 1909 ,Kindle for PC 1.24.3

**Comment by norbusan** [comment]
Yes, that is the reason why there is [WIP] - the conversion of the DRM code is a huge pain, because it uses a lot of bytes/strings which means that conversion to Py3 is difficult.

**Comment by apprenticeharper** [comment]
Conversion to Python 3 is on my list, but I have little time.

**Comment by apprenticeharper** [comment]
I have made a Python3 branch. Please do retain 2.7 compatibility, and make a pull request on that branch, if possible one pull request per tool.

Please only spend time on the plugin files. The stand alone apps are going to be dropped.

**Comment by apprenticeharper** [comment]
Please resubmit (I suggest in parts) against Python 3 branch

**Pull request closed without merging**
