### PR TITLE
Support HD image container for some Amazon Kindle (Mobi) books

### PR DESCRIPTION
**Pull request by choryuidentify**
1 years ago, I'm open the issue #483 
After some investigation, I found the tool 'DumpAZW6', but It's a 'dumper', not `merger`.
so I've decide intergrate image merger into DeDRM tool, and finally done it.

I just testing some Japanese Lightnovels and It looks work good, but Please test this patch If you have .azw and .azw.res both. It's basically encrypted Amazon Kindle book, and exists in same folder (Kindle Library).

You can test this patch [here](https://github.com/choryuidentify/DeDRM_tools/releases/tag/v6.6.3-patched). It's a Calibre plugin.

### CODE REVIEW

**Comment by choryuidentify** [comment]
HD Image container (.azw.res) file will be generated recent version of Kindle for PC, like 1.21. It is generate the '.azw.res' but 1.16 does not.
Old Kindle for PC just download main book, so Image is lower resolution.

**Comment by j-howell** [comment]
It has been a long time since any pull requests have been accepted for this project. And even if they were being actively added, this change has nothing to do with DRM removal. You should consider implementing this functionality as a separate calibre plugin. 

Since it is not DRM related it could be included along with all of the other calibre plugins that are managed and updated via the standard calibre plugin interface. And you would not be dependant on anyone else to make further updates available. Anyone can add calibre plugins that are not DRM-related here: https://www.mobileread.com/forums/forumdisplay.php?f=237

**Comment by choryuidentify** [comment]
> 
> 
> It has been a long time since any pull requests have been accepted for this project. And even if they were being actively added, this change has nothing to do with DRM removal. You should consider implementing this functionality as a separate calibre plugin.
> 
> Since it is not DRM related it could be included along with all of the other calibre plugins that are managed and updated via the standard calibre plugin interface. And you would not be dependant on anyone else to make further updates available. Anyone can add calibre plugins that are not DRM-related here: https://www.mobileread.com/forums/forumdisplay.php?f=237

I don't think so.
.azw.res file is never generated or served with 'user custom mobi file' like by kindlegen, or calibre.
.azw.res file always served WITH DRM-ed mobi file. and many people can't know this problem. because it just works fine without this image container, but lower resolution.

So, well, separate plug-in is not an option.

Thanks to your reply!

**Comment by apprenticeharper** [comment]
I'm with jhowell on this one. A separate plugin that merges the high-res images in from from .res file sounds like a better bet to me.

The less that there is to maintain in this project, the better.

**Comment by choryuidentify** [comment]
> 
> 
> I'm with jhowell on this one. A separate plugin that merges the high-res images in from from .res file sounds like a better bet to me.
> 
> The less that there is to maintain in this project, the better.

Well, ok. I close this request.

**Pull request closed without merging**
