### PR TITLE
add support for linux via device serials and reading from device

### PR DESCRIPTION
**Pull request by norbusan**
Hi

I have added support for Linux and decrypting from the device into the obok calibre plugin. The configuration dialog has been extended to add a serial number configuration dialog, copied (and modified) from the DeDRM config.py code.

The only thing that is still open, and I have no idea how this could easily be done, is the configuration of the PATH to the sqlite library. In the version here there is one line marked with TODO TODO, where simply my own mount point is entered.

This should be read from calibre if a device is plugged in. If you can tell me how to check for a plugged in device that Calibre recognizes, I can make the necessary changes.

On my local test machine I could add books via the obok button to my Calibre library and the drm was correctly removed.

Thanks

### CODE REVIEW

**Comment by apprenticeharper** [comment]
Very impressive. This should certainly appear in a future version of the tools once it's been made generic.

**Comment by norbusan** [comment]
Can you give me a hint how to get the connect device path from calibre? Then I can extended it to work more easily. And I also thought about allowing device retrieval for Windows and Mac.

**Comment by apprenticeharper** [comment]
I suggest that you ask at the calibre dev forum at MobileRead, where they'll be happy to discuss this kind of thing so long as it's not explicitly about DRM removal. And the people that hang out there know an awful lot more about calibre and kobo devices than I do.

**Comment by apprenticeharper** [comment]
I'm rather new to github, but it looks like I can't accept this pull request except into the master branch. I'd much rather work on this in a 'kobo-device' branch before merging into the master release branch. Can you change this pull request? Should I make such a branch first? I don't know the best way to proceed here.

**Comment by norbusan** [comment]
Hi
thanks, I will contact the MobileRead forum.

Concerning the branch: You need to create a branch first, otherwise I cannot send a pull request. So if you create a branch you prefer, I can send a pull request to that branch, and you close this one.

Another option is that you pull it manually, looking at https://help.github.com/articles/checking-out-pull-requests-locally/ is should be possible.

Hope that helps

Norbert

PS: I am doing all the things by hand ;-)

**Comment by norbusan** [comment]
BTW,  I have now updated my branch to include all the requested features:
* device path is read from calibre when a device is plugged in
* on Windows and Mac: first try to use Kobo Desktop, if that is not installed, check for connected device, if all fails, give a warning

I have tested the plugin as follows:
* linux: no Kobo Desktop, device plugged in
* Windows: Kobo Desktop installed, device NOT plugged in
* Mac: no Kobo Desktop, device plugged in
in all cases removal of DRM worked without a problem.

I hope that satisfies your needs. Let me know to which branch I should send the patches.

**Comment by apprenticeharper** [comment]
I have done a manual pull and push, so there is now a branch here with your code in it. Checking other kobo plugins at MobileRead, I find that one seems to be able to pull the Kobo device serial number off the kobo without user intervention. See the thread about the Kobo Utilities plugin., and especially this post:

http://www.mobileread.com/forums/showthread.php?p=2941220#post2941220

Retrieving the serial n umber automatically would obviously be much better.

**Comment by norbusan** [comment]
Oh, that is cool. I will look into it and see if that can be automated. That would drop the full lengthy part on the serial editing interface.

Thanks for looking into it.

**Comment by apprenticeharper** [comment]
If you agree, I think it might be better to always gets books for import from a Kobo device if one's present, and only go to the desktop database if there's no device connected.

**Comment by apprenticeharper** [comment]
I noticed in the code changes that you'd added back in a conversion to ascii, ignore. I had thought that the fix from the other scripts would have fixed that. Ah - but perhaps it requires all the print output to be unicode strings. I think that would be better, so I'll swap to that once I get your next code update.

**Comment by norbusan** [comment]
I am closing this pull request since you merged it manually into a different branch.

I open a new one concerning the above changes, and will answer there.

**Pull request closed without merging**
